 name: Run release-please
 on:
   push:
     branches:
       - master
 jobs:
   release-please:
     runs-on: ubuntu-latest
     steps:
       - uses: GoogleCloudPlatform/release-please-action@v3.4.1
         with:
           token: ${{ secrets.GITHUB_TOKEN }}
           release-type: simple
